<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tblpagetemplate"
 *
 * Auto generated by Extension Builder 2017-05-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'tblPageTemplate',
    'description' => 'my first pageTemplate',
    'category' => 'distribution',
    'author' => 'Thorsten Blei',
    'author_email' => '',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-7.6.99',
			'version' => '',
			'vhs' => '',
			'flux' => '',
			'fluid' => '',
			'formhandler' => '',
			'realurl' => '',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
